"use strict";
function grid(c,w,h){c.strokeStyle="rgba(255,255,255,.05)";c.lineWidth=1;for(let y=35;y<h;y+=35){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}}
function drawTrendCanvas(ctx,canvas,final=false){let w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);grid(ctx,w,h);let a=hist.slice(final?-80:-55);if(a.length>1){let vs=a.map(p=>p.bpm),lo=Math.min(...vs)-8,hi=Math.max(...vs)+8;if(hi-lo<16){lo-=8;hi+=8}ctx.strokeStyle="#f5f7fb";ctx.lineWidth=2;ctx.beginPath();a.forEach((p,i)=>{let x=i/(a.length-1)*w,y=h-14-(p.bpm-lo)/(hi-lo)*(h-30);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
 if(respHist.length>1){let r=respHist.slice(final?-30:-18),lo=6,hi=30;ctx.strokeStyle="#55c8ff";ctx.lineWidth=2;ctx.beginPath();r.forEach((p,i)=>{let x=i/(Math.max(1,r.length-1))*w,y=h-14-(p.rpm-lo)/(hi-lo)*(h-30);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}}
function draw(){let w=u.ppg.clientWidth,h=u.ppg.clientHeight;pc.clearRect(0,0,w,h);grid(pc,w,h);let f=pulseSignal(10000);if(f){let a=f.x.slice(-260);pc.strokeStyle="#ff4f6b";pc.lineWidth=2;pc.beginPath();a.forEach((v,i)=>{let x=i/(a.length-1)*w,y=h*.56-clamp(v,-2.5,2.5)*h*.15;i?pc.lineTo(x,y):pc.moveTo(x,y)});pc.stroke()}drawTrendCanvas(tc,u.trend,false);if(!u.report.classList.contains("hidden"))drawTrendCanvas(fc,u.finalTrend,true)}
function resize(){for(const [c,x] of [[u.ppg,pc],[u.trend,tc],[u.finalTrend,fc]]){let r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;x.setTransform(d,0,0,d,0,0)}draw()}
function loop(now){if(!stream||stopped)return;totalFrames++;fpsq.push(now);fpsq=fpsq.filter(t=>now-t<2000);if(fpsq.length>2)u.fps.textContent=((fpsq.length-1)/((fpsq.at(-1)-fpsq[0])/1000)).toFixed(1);let f=frame();if(!f){next();return}u.finger.textContent=f.finger?"SÌ":"NO";if(f.finger){if(!fingerAt)fingerAt=now;lostAt=0}else{fingerAt=0;if(!lostAt)lostAt=now}
 if(mode==="arm"){u.ostate.textContent=f.finger?"Dito rilevato · resta fermo":"Cerco il dito…";if(f.finger&&now-fingerAt>700){mode="run";startAt=now;samples=[];hist=[];good=[];qualityScores=[];validFrames=0;u.overlay.classList.add("hidden");u.status.textContent="Misurazione reale in corso";u.phase.textContent="misurazione";u.anatomyStage.classList.add("active");u.hudLiveText.textContent="Analisi PPG in corso"}}
 else if(mode==="run"){if(f.finger){validFrames++;samples.push({t:now,v:f.v,r:f.r,g:f.g,b:f.b,bright:f.bright});let e=now-startAt;u.timer.textContent=u.hudTimer.textContent=fmt(D-e);analyse(now);if(e>=D){finish(false);return}}else if(lostAt&&now-lostAt>1800){finish(true,"Dito perso durante la misura. Riprova mantenendo lente e flash coperti.");return}}next()}
function next(){if(!stream||stopped)return;if("requestVideoFrameCallback" in HTMLVideoElement.prototype)u.video.requestVideoFrameCallback(()=>loop(performance.now()));else requestAnimationFrame(loop)}
async function countdown(){u.overlay.classList.remove("hidden");for(let n=5;n>=1;n--){u.count.textContent=n;await new Promise(r=>setTimeout(r,1000));if(stopped)return false}u.count.textContent="✓";return true}
async function shutdown(){mode="idle";stopped=true;if(track&&on)try{await track.applyConstraints({advanced:[{torch:false}]})}catch{}on=false;u.torch.textContent="OFF";if(stream)stream.getTracks().forEach(t=>t.stop());stream=track=null;u.video.srcObject=null;u.overlay.classList.add("hidden");u.stop.classList.add("hidden");u.start.classList.remove("hidden");u.test.classList.remove("hidden");u.start.disabled=u.test.disabled=false}
async function begin(){hide();reset();stopped=false;u.start.disabled=u.test.disabled=true;u.start.classList.add("hidden");u.test.classList.add("hidden");u.stop.classList.remove("hidden");u.status.textContent="Cerco fotocamera con torcia…";try{await findTorchCam();await setTorch(true);u.status.textContent="Torcia accesa";next();if(!await countdown())return;mode="arm";u.ostate.textContent="Verifico il dito…"}catch(e){let t=e.message==="HTTPS"?"Serve HTTPS aperto in Safari: l’anteprima interna non può concedere fotocamera e torcia.":e.message==="NOTORCH"?"Safari non ha esposto una fotocamera con torcia.":"Errore: "+(e.message||e.name);msg(t,true);u.status.textContent="Misura non avviata";await shutdown()}}
async function test(){hide();stopped=false;u.start.disabled=u.test.disabled=true;u.status.textContent="Test torcia…";try{await findTorchCam();await setTorch(true);u.status.textContent="TORCIA ACCESA";msg("Controlla il retro dell’iPhone: la luce resta accesa 8 secondi.");await new Promise(r=>setTimeout(r,8000));await shutdown();u.status.textContent="Test completato"}catch(e){msg("Test luce fallito: "+(e.message||e.name),true);await shutdown()}}
function buildReport(){let bpmVals=good.filter(Number.isFinite),bpmMed=bpmVals.length?Math.round(med(bpmVals)):null,bpmMin=bpmVals.length?Math.round(Math.min(...bpmVals)):null,bpmMax=bpmVals.length?Math.round(Math.max(...bpmVals)):null;let f=pulseSignal(26000),hm=f?hrvMetrics(f):null,rhythm=f?rhythmScreen(f):null,rr=hm?Math.round(hm.rr):null,rmssd=hm&&Number.isFinite(hm.rmssd)?Math.round(hm.rmssd):null,sdnn=hm&&Number.isFinite(hm.sdnn)?Math.round(hm.sdnn):null,pnn50=hm&&Number.isFinite(hm.pnn50)?Math.round(hm.pnn50):null;let resp=respirationEstimate(),m=morphology(),oxy=oxygenationResearch(),qmed=qualityScores.length?med(qualityScores):0,qText=qmed>.62?"Ottima":qmed>.45?"Buona":qmed>.30?"Discreta":"Bassa",qLevel=qmed>.62?5:qmed>.50?4:qmed>.38?3:qmed>.28?2:1;let validPct=totalFrames?Math.round(validFrames/totalFrames*100):0,avgFps=fpsq.length>2?((fpsq.length-1)/((fpsq.at(-1)-fpsq[0])/1000)):NaN;
 u.reportStamp.innerHTML=new Date().toLocaleDateString("it-IT")+"<br>sessione 30 s";u.reportBpm.innerHTML=(bpmMed??"--")+' <small>BPM medi</small>';u.reportRange.textContent=bpmMin!=null?`Range ${bpmMin}–${bpmMax} BPM`:"Range non disponibile";u.repRR.textContent=rr!=null?rr+" ms":"--";u.repRMSSD.textContent=rmssd!=null?rmssd+" ms":"--";u.repSDNN.textContent=sdnn!=null?sdnn+" ms":"Non stimabile";u.repPNN50.textContent=pnn50!=null?pnn50+" %":"Non stimabile";u.repMin.textContent=bpmMin!=null?bpmMin+" BPM":"--";u.repMax.textContent=bpmMax!=null?bpmMax+" BPM":"--";
 let rhythmOk=rhythm&&qmed>.30;u.repRhythm.textContent=rhythmOk?rhythm.label:"Non valutabile";u.repRhythmSub.textContent=rhythmOk?`indice euristico ${Math.round(rhythm.score)}/100 · non diagnostica FA`:"qualità/durata non sufficienti per screening";
 u.repResp.textContent=resp?Math.round(resp.rpm)+" atti/min":"Non stimabile";u.repRespQ.textContent=resp?(resp.score>.46?"Buona":resp.score>.30?"Discreta":"Bassa"):"Insufficiente";u.repRespSub.textContent=resp?`componenti coerenti: ${resp.components.join(" + ")}`:"baseline / ampiezza / IBI non sufficientemente coerenti";
 u.repRise.textContent=m&&m.rise?Math.round(m.rise)+" ms":"Non stimabile";u.repWidth.textContent=m&&m.width?Math.round(m.width)+" ms":"Non stimabile";u.repACDC.textContent=m&&Number.isFinite(m.acdc)?m.acdc.toFixed(2)+" %":"Non stimabile";u.repNotch.textContent=m?m.notch:"Non stimabile";
 u.repOxyRG.textContent=oxy?oxy.ratio.toFixed(3):"Non stimabile";u.repOxyState.textContent=oxy?oxy.state:"Non valutabile";u.repSpO2.textContent="Non riportata";u.repBP.textContent="Non stimata";
 u.repQuality.textContent=qText;[...u.qualityDots.children].forEach((d,i)=>d.classList.toggle("on",i<qLevel));u.repValid.textContent=validPct+" %";u.repFps.textContent="FPS finali: "+(Number.isFinite(avgFps)?avgFps.toFixed(1):u.fps.textContent);
 u.report.classList.remove("hidden");u.report.classList.add("reveal");u.anatomyStage.classList.remove("active");setTimeout(()=>{resize();drawTrendCanvas(fc,u.finalTrend,true);u.report.scrollIntoView({behavior:"smooth",block:"start"})},180)}
async function finish(fail,text=""){if(fail){msg(text||"Segnale insufficiente.",true);u.status.textContent="Misura annullata"}else if(good.length>=5){let b=Math.round(med(good));u.bpm.textContent=u.avg.textContent=b;u.timer.textContent="00:00";u.phase.textContent="completata";u.status.textContent="Misurazione completata · REPORT PRONTO";msg("Sessione completata. I valori derivano esclusivamente dai frame acquisiti; le stime non affidabili vengono marcate come non stimabili.");buildReport()}else{msg("Segnale PPG insufficiente: nessun risultato viene simulato.",true);u.status.textContent="Segnale insufficiente"}await shutdown()}
u.start.onclick=begin;u.test.onclick=test;u.stop.onclick=async()=>{msg("Misurazione interrotta.");await shutdown()};u.newMeasure.onclick=()=>{u.report.classList.add("hidden");reset();window.scrollTo({top:0,behavior:"smooth"})};window.onresize=resize;document.addEventListener("visibilitychange",()=>{if(document.hidden&&stream)shutdown()});resize();
