"use strict";
const D=30000,MIN=45,MAX=190,W=14000;
const $=x=>document.getElementById(x),u={start:$("start"),test:$("test"),stop:$("stop"),newMeasure:$("newMeasure"),status:$("status"),bpm:$("bpm"),avg:$("avg"),timer:$("timer"),phase:$("phase"),quality:$("quality"),rr:$("rr"),rmssd:$("rmssd"),rhythm:$("rhythm"),oxyResearch:$("oxyResearch"),torch:$("torch"),finger:$("finger"),fps:$("fps"),ppg:$("ppg"),trend:$("trend"),sample:$("sample"),video:$("video"),overlay:$("overlay"),count:$("count"),ostate:$("ostate"),msg:$("msg"),report:$("report"),reportStamp:$("reportStamp"),reportBpm:$("reportBpm"),reportRange:$("reportRange"),repRR:$("repRR"),repRMSSD:$("repRMSSD"),repSDNN:$("repSDNN"),repPNN50:$("repPNN50"),repMin:$("repMin"),repMax:$("repMax"),repRhythm:$("repRhythm"),repRhythmSub:$("repRhythmSub"),repLFHF:$("repLFHF"),repResp:$("repResp"),repRespQ:$("repRespQ"),repRespSub:$("repRespSub"),repRise:$("repRise"),repWidth:$("repWidth"),repACDC:$("repACDC"),repNotch:$("repNotch"),repOxyRG:$("repOxyRG"),repOxyState:$("repOxyState"),repSpO2:$("repSpO2"),repBP:$("repBP"),repQuality:$("repQuality"),qualityDots:$("qualityDots"),repValid:$("repValid"),repFps:$("repFps"),anatomyStage:$("anatomyStage"),hudTimer:$("hudTimer"),hudLiveText:$("hudLiveText"),hudBpm:$("hudBpm"),hudResp:$("hudResp"),finalTrend:$("finalTrend")};
const sc=u.sample.getContext("2d",{willReadFrequently:true}),pc=u.ppg.getContext("2d"),tc=u.trend.getContext("2d"),fc=u.finalTrend.getContext("2d");
let stream=null,track=null,on=false,mode="idle",samples=[],hist=[],respHist=[],good=[],fpsq=[],startAt=0,fingerAt=0,lostAt=0,lastA=0,lastRespAt=0,stopped=false,totalFrames=0,validFrames=0,qualityScores=[];
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,sd=a=>{if(a.length<2)return 0;let m=mean(a);return Math.sqrt(mean(a.map(v=>(v-m)**2)))},med=a=>{if(!a.length)return NaN;let b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2},clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function msg(t,bad=false){u.msg.textContent=t;u.msg.className="msg"+(bad?" bad":"")}function hide(){u.msg.className="msg hidden"}
function reset(){samples=[];hist=[];respHist=[];good=[];fpsq=[];qualityScores=[];totalFrames=validFrames=0;u.bpm.textContent=u.avg.textContent=u.quality.textContent="--";u.rr.innerHTML='-- <small>ms</small>';u.rmssd.innerHTML='-- <small>ms</small>';u.rhythm.textContent="--";u.rhythm.className="val";u.oxyResearch.textContent="--";u.timer.textContent=u.hudTimer.textContent="00:30";u.phase.textContent="durata misura";u.finger.textContent=u.fps.textContent="--";u.hudBpm.textContent=u.hudResp.textContent="--";u.hudLiveText.textContent="In attesa del segnale";u.anatomyStage.classList.remove("active");u.anatomyStage.style.setProperty("--beat",".85s");u.anatomyStage.style.setProperty("--breath","4.6s");u.report.classList.add("hidden");u.report.classList.remove("reveal");draw()}
function fmt(ms){let s=Math.max(0,Math.ceil(ms/1000));return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
async function attach(s){if(stream)stream.getTracks().forEach(t=>t.stop());stream=s;track=s.getVideoTracks()[0];u.video.srcObject=s;await u.video.play();await new Promise(r=>setTimeout(r,140))}
function torchCap(t){try{return t.getCapabilities?.().torch===true}catch{return false}}async function cam(c){return navigator.mediaDevices.getUserMedia({audio:false,video:c})}
function score(l=""){l=l.toLowerCase();return(/back|rear|posteriore|environment/.test(l)?10:0)+(/wide|grandang/.test(l)?2:0)-(/front|anteriore|facetime/.test(l)?20:0)}
async function findTorchCam(){if(!window.isSecureContext)throw Error("HTTPS");if(!navigator.mediaDevices?.getUserMedia)throw Error("NOAPI");try{let s=await cam({facingMode:{ideal:"environment"},width:{ideal:640},height:{ideal:480},frameRate:{ideal:30,max:60}});await attach(s);if(torchCap(track))return}catch(e){}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;track=null}let ds=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==="videoinput");ds.sort((a,b)=>score(b.label)-score(a.label));for(const d of ds){let s;try{s=await cam({deviceId:{exact:d.deviceId},width:{ideal:640},height:{ideal:480},frameRate:{ideal:30,max:60}});let t=s.getVideoTracks()[0];if(torchCap(t)){await attach(s);return}s.getTracks().forEach(x=>x.stop())}catch(e){if(s)s.getTracks().forEach(x=>x.stop())}}throw Error("NOTORCH")}
async function setTorch(v){if(!track||!torchCap(track))throw Error("NOTORCH");await track.applyConstraints({advanced:[{torch:!!v}]});on=!!v;u.torch.textContent=v?"ON":"OFF"}
function frame(){if(!u.video.videoWidth)return null;sc.drawImage(u.video,0,0,48,36);let d=sc.getImageData(0,0,48,36).data,r=0,g=0,b=0,n=0,sat=0;for(let i=0;i<d.length;i+=4){r+=d[i];g+=d[i+1];b+=d[i+2];if(d[i]>249||d[i+1]>249||d[i+2]>249)sat++;n++}r/=n;g/=n;b/=n;sat/=n;let bright=(r+g+b)/3,red=r/Math.max(1,(g+b)/2);let finger=r>65&&bright>25&&red>1.08&&sat<.97;let denom=Math.max(1,r+g+b);return{finger,r,g,b,sat,bright,red,v:g/denom}}
function resamp(ms=W,field="v"){if(samples.length<50)return null;let now=samples.at(-1).t,a=samples.filter(s=>now-s.t<=ms&&Number.isFinite(s[field]));if(a.length<50)return null;let dur=(a.at(-1).t-a[0].t)/1000,fs=clamp((a.length-1)/Math.max(.001,dur),15,60),step=1000/fs,out=[],j=0;for(let t=a[0].t;t<=a.at(-1).t;t+=step){while(j<a.length-2&&a[j+1].t<t)j++;let x=a[j],y=a[j+1],q=(t-x.t)/Math.max(1,y.t-x.t);out.push(x[field]+(y[field]-x[field])*clamp(q,0,1))}return{x:out,fs}}
function pulseSignal(ms=W){let rs=resamp(ms,"v");if(!rs||rs.x.length<60)return null;let x=rs.x,fs=rs.fs,win=Math.max(5,Math.round(fs*.9)),sum=0,z=[];for(let i=0;i<x.length;i++){sum+=x[i];if(i>=win)sum-=x[i-win];z[i]=x[i]-sum/Math.min(i+1,win)}z=z.map((v,i)=>(z[Math.max(0,i-1)]+2*v+z[Math.min(z.length-1,i+1)])/4);let s=sd(z);if(s<1e-7)return null;return{x:z.map(v=>v/s),fs,raw:x}}
function detectPeaks(f){if(!f)return[];let x=f.x,fs=f.fs,p=[],dist=Math.round(fs*60/MAX),last=-999;for(let i=2;i<x.length-2;i++){if(x[i]>.18&&x[i]>=x[i-1]&&x[i]>x[i+1]&&i-last>=dist){if(p.length&&i-p.at(-1)<Math.round(fs*.16)){if(x[i]>x[p.at(-1)])p[p.length-1]=i}else p.push(i);last=p.at(-1)}}return p}
function peakIntervals(f){let p=detectPeaks(f),q=[];for(let i=1;i<p.length;i++){let m=(p[i]-p[i-1])*1000/f.fs,b=60000/m;if(b>=MIN&&b<=MAX)q.push(m)}if(q.length>=3){let m=med(q);q=q.filter(v=>Math.abs(v-m)<m*.25)}return q}
function rawPeakIntervals(f){let p=detectPeaks(f),q=[];for(let i=1;i<p.length;i++){let m=(p[i]-p[i-1])*1000/f.fs,b=60000/m;if(b>=MIN&&b<=MAX)q.push(m)}return q}
function hrvMetrics(f){let ints=peakIntervals(f);if(ints.length<3)return null;let diffs=[];for(let i=1;i<ints.length;i++)diffs.push(ints[i]-ints[i-1]);let rmssd=diffs.length?Math.sqrt(mean(diffs.map(v=>v*v))):null,sdnn=sd(ints),pnn50=diffs.length?diffs.filter(v=>Math.abs(v)>50).length/diffs.length*100:null;return{ints,rr:med(ints),rmssd,sdnn,pnn50}}
function rhythmScreen(f){let ints=rawPeakIntervals(f);if(ints.length<8)return null;let m=med(ints),mad=med(ints.map(v=>Math.abs(v-m))),robustCv=m?1.4826*mad/m:1,out=ints.filter(v=>Math.abs(v-m)>m*.18).length/ints.length,score=clamp(robustCv*280+out*90,0,100);let label=score<18?"Regolare":score<35?"Variabile":"Da verificare";return{label,score,robustCv,out,n:ints.length}}
function movingMean(arr,n){let o=[],s=0;for(let i=0;i<arr.length;i++){s+=arr[i];if(i>=n)s-=arr[i-n];o.push(s/Math.min(i+1,n))}return o}
function slowRate(arr,fs,minRpm=6,maxRpm=30){if(!arr||arr.length<Math.max(30,fs*10))return null;let trend=movingMean(arr,Math.max(3,Math.round(fs*6))),y=arr.map((v,i)=>v-trend[i]),sy=sd(y);if(sy<1e-8)return null;y=y.map(v=>v/sy);let minLag=Math.max(2,Math.floor(fs*60/maxRpm)),maxLag=Math.min(y.length-4,Math.ceil(fs*60/minRpm)),best=-9,lag=0;for(let l=minLag;l<=maxLag;l++){let n=0,a=0,b=0;for(let i=l;i<y.length;i++){n+=y[i]*y[i-l];a+=y[i]*y[i];b+=y[i-l]*y[i-l]}let c=n/Math.max(1e-9,Math.sqrt(a*b));if(c>best){best=c;lag=l}}if(!lag)return null;let rpm=60*fs/lag;if(rpm<minRpm||rpm>maxRpm)return null;return{rpm,score:best}}
function interpolatePoints(points,fs=4){if(!points||points.length<5)return null;let t0=points[0].t,t1=points.at(-1).t;if(t1-t0<10000)return null;let step=1000/fs,out=[],j=0;for(let t=t0;t<=t1;t+=step){while(j<points.length-2&&points[j+1].t<t)j++;let a=points[j],b=points[j+1],q=(t-a.t)/Math.max(1,b.t-a.t);out.push(a.v+(b.v-a.v)*clamp(q,0,1))}return{x:out,fs}}
function channelPulsatility(field,ms=26000){let rs=resamp(ms,field);if(!rs||rs.x.length<80)return null;let trend=movingMean(rs.x,Math.max(5,Math.round(rs.fs*1.4))),hp=rs.x.map((v,i)=>v-trend[i]),dc=mean(rs.x),ac=sd(hp);if(!Number.isFinite(dc)||dc<=1||!Number.isFinite(ac))return null;return{acdc:ac/dc,fs:rs.fs}}
function oxygenationResearch(){let r=channelPulsatility("r"),g=channelPulsatility("g");if(!r||!g||g.acdc<=1e-7)return null;let ratio=r.acdc/g.acdc;if(!Number.isFinite(ratio)||ratio<.05||ratio>8)return null;let half=Math.floor(samples.length/2),calcHalf=(arr)=>{if(arr.length<80)return null;let vals={};for(const field of ["r","g"]){let x=arr.map(s=>s[field]).filter(Number.isFinite),dc=mean(x);if(x.length<60||dc<=1)return null;let n=Math.max(5,Math.round(x.length/Math.max(8,(arr.at(-1).t-arr[0].t)/1000)*1.4)),tr=movingMean(x,n),hp=x.map((v,i)=>v-tr[i]);vals[field]=sd(hp)/dc}return vals.g>1e-7?vals.r/vals.g:null};let a=calcHalf(samples.slice(0,half)),b=calcHalf(samples.slice(half)),drift=(Number.isFinite(a)&&Number.isFinite(b))?Math.abs(a-b)/Math.max(.001,(a+b)/2):null;return{ratio,drift,state:drift==null?"Non valutabile":drift<.18?"Stabile":drift<.35?"Variabile":"Instabile"}}
function autocorrBpm(){let f=pulseSignal();if(!f)return null;let x=f.x,fs=f.fs,min=Math.floor(fs*60/MAX),max=Math.ceil(fs*60/MIN),best=-9,lag=0;for(let l=min;l<=max;l++){let n=0,a=0,b=0;for(let i=l;i<x.length;i++){n+=x[i]*x[i-l];a+=x[i]*x[i];b+=x[i-l]*x[i-l]}let c=n/Math.max(1e-9,Math.sqrt(a*b));if(c>best){best=c;lag=l}}if(!lag)return null;return{bpm:60*fs/lag,score:best,f}}
